### ISSUE TITLE
ExAndroidNativeEmu ? 

### ISSUE THREAD

**Issue by gaplan** [hazen1314/dy233_unidbg_sign#2]
Hello,
Can we do this using ExAndroidNativeEmu instead of using unidbg?
And do you use telegram?

**Comment by hazen1314** [comment]
> Hello, Can we do this using ExAndroidNativeEmu instead of using unidbg? And do you use telegram?

https://github.com/hazen1314/dy233_androidNativeEmu_sign

**Comment by gaplan** [comment]
Thanx
